id = "relview"
name = "RelView"
version = "0.0.1"
schema_version = 1
authors = ["Benjamin Davies <bentendavies@gmail.com>"]
description = "RelView language support."
repository = "https://github.com/Benjamin-Davies/zed-relview"

[grammars.relview]
repository = "https://github.com/Benjamin-Davies/tree-sitter-relview"
rev = "12b6c1326f9c011b63b7754612618f96efd56292"
